build.dependencies.gradle

and FTC Dashboard
without extra configuration

make RoadRunner downloadable in certain network

---

ForTeaching/src/main/java/org/firstinspires/ftc/forteaching/TechnoBot/Commands/TankDriveCommand.java
ForTeaching/src/main/java/org/firstinspires/ftc/forteaching/TechnoBot/Commands/VisionCommand.java
ForTeaching/src/main/java/org/firstinspires/ftc/forteaching/TechnoBot/Controls.java
ForTeaching/src/main/java/org/firstinspires/ftc/forteaching/TechnoBot/Hardware.java
ForTeaching/src/main/java/org/firstinspires/ftc/forteaching/TechnoBot/OpModes/TechnoManualControl.java
ForTeaching/src/main/java/org/firstinspires/ftc/forteaching/TechnoBot/Subsystems/TankDriveSubsystem.java
ForTeaching/src/main/java/org/firstinspires/ftc/forteaching/TechnoBot/Subsystems/VisionPipeline.java
ForTeaching/src/main/java/org/firstinspires/ftc/forteaching/TechnoBot/Subsystems/VisionSubsystem.java
ForTeaching/src/main/java/org/firstinspires/ftc/forteaching/TechnoBot/TheBot.java
build.dependencies.gradle

This is all working on the over-the-summer bott

Vision subsystem is operational, as is the FTC Dashboard

---

build.common.gradle
build.dependencies.gradle
build.gradle

I also removed the unused 'libs' reference in gradle files (because repetitive warnings annoy me very much)

Update version of TechnoLib

---

ForTeaching/src/main/java/org/firstinspires/ftc/forteaching/TechnoBot/Controls.java
ForTeaching/src/main/java/org/firstinspires/ftc/forteaching/TechnoBot/OpModes/TechnoManualControl.java
ForTeaching/src/main/java/org/firstinspires/ftc/forteaching/TechnoBot/Subsystems/VisionPipeline.java
ForTeaching/src/main/java/org/firstinspires/ftc/forteaching/TechnoBot/Subsystems/VisionSubsystem.java
ForTeaching/src/main/java/org/firstinspires/ftc/forteaching/TechnoBot/TheBot.java

Vision code structured for teaching

---

Twenty403/src/main/java/org/firstinspires/ftc/twenty403/Controls.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/Robot.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/drive/DriveCommand.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/drive/ResetGyroCommand.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/drive/SetSpeedCommand.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystem/DrivebaseSubsystem.java

10/4/2022: more Controls code for twenty403

---

README.md
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/command/autonomous/AutoConstantsRed.java

Moving Friday evening's work into main

Sree's branch merge

---

Twenty403/src/main/java/org/firstinspires/ftc/twenty403/Controls.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/Hardware.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/Robot.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmode/BlackTeleOpMode.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmode/PLACEHOLDER
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystem/PLACEHOLDER

Created a OpMode and update hardware mapping for Twenty403
but had to disable two buttons to mitigate a NullPointerException

make Twenty403's wheels rotate

---

build.gradle

current configuration included build output directories
also excluded files that being frequently modify by multiple users to reduce merge conflicts

exclude some files for spotless

---

Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystem/DrivebaseSubsystem.java

We ran the drivebase constants configurator doohickey here: https://learnroadrunner.com/drive-constants.html#drive-constants and measured the robot, and updated stuff accordingly.

Updated the drivebase constants

---

Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/subsystem/ClawSubsystem.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystem/ClawSubsystem.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystem/LiftSubsystem.java

Changes to make subsystems "work" even without hardware

---

Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/Hardware.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/command/autonomous/blue_away/AutoBlueAwayConeStackCommand.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/command/autonomous/blue_away/AutoBlueAwayGroup.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/command/autonomous/blue_home/AutoBlueHomeConeStackCommand.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/command/autonomous/blue_home/AutoBlueHomeGroup.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/command/autonomous/red_away/AutoRedAwayConeStackCommand.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/command/autonomous/red_away/AutoRedAwayGroup.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/command/autonomous/red_home/AutoRedHomeConeStackCommand.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/command/autonomous/red_home/AutoRedHomeGroup.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/autonomous/blue_away/AutoBlueAwayConeStackCommand.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/autonomous/blue_away/AutoBlueAwayGroup.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/autonomous/blue_home/AutoBlueHomeConeStackCommand.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/autonomous/blue_home/AutoBlueHomeGroup.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/autonomous/red_away/AutoRedAwayConeStackCommand.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/autonomous/red_away/AutoRedAwayGroup.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/autonomous/red_home/AutoRedHomeConeStackCommand.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/autonomous/red_home/AutoRedHomeGroup.java

Much easier to find AutoConstantsRed and AutoConstantsBlue
~Awaiting changes from [freik branch](https://github.com/technototes/PowerPlay2022/tree/freik) to be merged, then I will make the same change to Sixteen750~

Put Auto{Color}{Side}Group to corresponding folders/directories

---

branches.txt
merge.bat

This is just a helpful script once a PR into main has been made to merge those changes into all other branches. If there's a new branch that we want to keep update, add it to the 'branches.txt' file.

Added my merge main into every other branch script

---

Twenty403/src/main/java/org/firstinspires/ftc/twenty403/Hardware.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/Robot.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/VisionCommand.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/autonomous/AutoConstantsBlue.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/autonomous/AutoTestDrivebaseCommand.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/autonomous/StartingPosition.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmode/BlackTeleOpMode.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmode/DrivebaseTestAutoOpMode.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmode/LiftTestTeleOpMode.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmode/SimpleAutoOpMode.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystem/VisionPipeline.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystem/VisionSubsystem.java
branches.txt

Some stuff for Vision

---

Twenty403/src/main/java/org/firstinspires/ftc/twenty403/Controls.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/Robot.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystem/LiftSubsystem.java

@Yinn333 , please check out the restructuring & cleanup for the Lift Subsystem. It would be great to get it tested on the bot. You can connect to the dashboard to disable the lift *motors* while still observing the encoder values. Connect your laptop to the bot's wifi and go to http://192.168.43.1:8080/dash , then change the "RobotContants -> LIFT_MOVE_MOTORS" boolean.

Untested stuff for Lift (with lots of cleanup)

---

Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/autonomous/AutoTestDrivebaseCommand.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/autonomous/blue_home/AutoBlueHomeLeft.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/autonomous/blue_home/AutoBlueHomeMiddle.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/autonomous/blue_home/AutoBlueHomeRight.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/lift/JunctionHeight.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/lift/LiftGroundJunctionCommand.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/lift/LiftHeightCommand.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/lift/LiftHighJunctionCommand.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/lift/LiftLowJunctionCommand.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/lift/LiftMidJunctionCommand.java

Command flexibility

---

Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystem/LiftSubsystem.java

Cone height for the code stack

doing collect command

---

Twenty403/src/main/java/org/firstinspires/ftc/twenty403/Controls.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/lift/JunctionHeight.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/lift/LiftHeightCommand.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/lift/LiftIntakeCommand.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystem/LiftSubsystem.java

Hoda's control binding is ready for testing

Finalized Controls

---

Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/autonomous/AutoConstantsRed.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmode/BlackTeleOpMode.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmode/DriveMotorTestOpMode.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmode/DrivebaseTestAutoOpMode.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmode/ManualTestingOpMode.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmode/SimpleTeleOpMode.java

A few pieces of work from Gabriel, plus disabling extra opmodes

Cleanup opmodes, getting ready for the meet

---

Twenty403/src/main/java/org/firstinspires/ftc/twenty403/Robot.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystem/ClawSubsystem.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystem/LiftSubsystem.java

Fixed a couple bugs that were causing problems

---

Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystem/ClawSubsystem.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystem/LiftSubsystem.java

Set claw & lift constants

---

Twenty403/src/main/java/org/firstinspires/ftc/twenty403/Controls.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/Hardware.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/Robot.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/autonomous/blue_away/AutoBlueAwayLeft.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/autonomous/blue_home/AutoBlueHomeFullCycleLeft.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/autonomous/blue_home/AutoBlueHomeFullCycleMiddle.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/autonomous/blue_home/AutoBlueHomeFullCycleRight.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/autonomous/blue_home/AutoBlueHomeParkingSelectionFullCycleCommand.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/lift/LiftMoveDownOverrideCommand.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/lift/LiftMoveUpOverrideCommand.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/lift/LiftSetZeroCommand.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmode/BlueHomeFullCycle.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmode/BlueHomeTerminal.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystem/LiftSubsystem.java

Yes, we tested this stuff on the robot :)

Saturday November 12th work

---

Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/ControlsDriver.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/ControlsOperator.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/DriverControls.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/Hardware.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/OperatorControls.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/Robot.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/command/claw/ElbowGroundIntakePositionCommand.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/command/lift/LiftCarryCommand.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/command/lift/LiftHighJunctionCommand.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/command/lift/LiftHighPoleCommand.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/command/lift/LiftIntakeCommand.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/opmode/PLACEHOLDER
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/opmode/auto/DangerousTankAuto.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/opmode/diagnosis/AbsoluteAnalogEncoderDebug.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/opmode/diagnosis/AllInOneDebug.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/opmode/diagnosis/ClawServoTest.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/opmode/diagnosis/DriveMotorTest.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/opmode/diagnosis/DriveServoTest.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/opmode/diagnosis/LiftMotorTest.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/opmode/diagnosis/SwerveInfinityStraightTest.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/opmode/diagnosis/TankInfinityStraightTest.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/opmode/teleop/BasicTankDriveOpMode.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/opmode/teleop/ExperimentalSwerveDrive.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/opmode/teleop/RegularTankDrive.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/subsystem/ClawSubsystem.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/subsystem/LiftSubsystem.java

Move files around to new folders

Post League Meet 1 for 16750

---

Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/Robot.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/opmode/diagnosis/AbsoluteAnalogEncoderDebug.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/opmode/diagnosis/ClawServoTest.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/opmode/diagnosis/DriveServoTest.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/opmode/diagnosis/LiftMotorTest.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/opmode/teleop/ExperimentalSwerveDrive.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/subsystem/SimpleSwerveDrivebaseSubsystem.java

RIP swerve

---

ForTeaching/src/main/java/org/firstinspires/ftc/forteaching/TechnoBot/Commands/MecDriveCommand.java
ForTeaching/src/main/java/org/firstinspires/ftc/forteaching/TechnoBot/Controls.java
ForTeaching/src/main/java/org/firstinspires/ftc/forteaching/TechnoBot/Hardware.java
ForTeaching/src/main/java/org/firstinspires/ftc/forteaching/TechnoBot/Subsystems/DrivebaseSubsystem.java
ForTeaching/src/main/java/org/firstinspires/ftc/forteaching/TechnoBot/TheBot.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystem/LiftSubsystem.java

PID tuning

---

ForTeaching/src/main/java/org/firstinspires/ftc/forteaching/TechnoBot/Controls.java
ForTeaching/src/main/java/org/firstinspires/ftc/forteaching/TechnoBot/TheBot.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/Controls/Controls.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/Hardware.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/Robot.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/autonomous/AutoConstantsBlue.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/autonomous/blue_away/AutoBlueAwayFullCycleLeft.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/autonomous/blue_away/AutoBlueAwayFullCycleMiddle.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/autonomous/blue_away/AutoBlueAwayFullCycleRight.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/autonomous/blue_home/AutoBlueHomeFullCycleLeft.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/autonomous/blue_home/AutoBlueHomeFullCycleMiddle.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/autonomous/blue_home/AutoBlueHomeFullCycleRight.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmode/DebugTeleOp.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmode/DualBlueTeleOp.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmode/DualRedTeleOp.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystem/ClawSubsystem.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystem/LiftSubsystem.java

This includes Gabriel's new auto work, Yinn's lift adjustments, plus the fancy new distance sensor with automatic claw closing capabilities (currently disabled for drive practice)

Saturday work

---

Twenty403/src/main/java/org/firstinspires/ftc/twenty403/Controls/ControlOperator.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/Controls/ControlsDriver.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/claw/ClawAutoCloseToggleCommand.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/drive/DriveCommand.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystem/ClawSubsystem.java

Auto claw closing function, with toggling mapped for both controllers

---

Twenty403/src/main/java/org/firstinspires/ftc/twenty403/Controls/ControlOperator.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/Controls/ControlsDriver.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/claw/ClawAutoCloseToggleCommand.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/drive/DriveCommand.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystem/ClawSubsystem.java

Enable the claw by default, update open servo pos

---

Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/autonomous/AutoConstantsBlue.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/autonomous/blue_away/AutoBlueAwayFullCycleMiddle.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmode/LeftFullCycle.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystem/ClawSubsystem.java

Yin's work from Sunday afternoon

---

MeepMeepTesting/src/main/java/com/example/meepmeeptesting/AutoConstantsBlue.java
MeepMeepTesting/src/main/java/com/example/meepmeeptesting/Sixteen750Testing.java
MeepMeepTesting/src/main/java/com/example/meepmeeptesting/Twenty403Testing.java

Split MeepMeepTesting for each robot

---

Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmode/ManualTestingOpMode.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmode/SimpleTeleOpMode.java

This is a manual teleop for adjusting drive motor power, without using RoadRunner.

Drive base adjustment teleop mode

---

Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/autonomous/AutoConstantsBlue.java

Parking works for left and right all three sides

---

.gitignore
branches.txt

\- [ ] This Pull-Request includes global changes that may affect other users

Helper script stuff

---

Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/autonomous/AutoConstantsBlue.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/autonomous/blue_home/AutoBlueHomeFullCycle.java

Gabriel's work for auto again

---

Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/autonomous/AutoConstantsBlue.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/autonomous/blue_home/AutoBlueHomeFullCycle.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystem/ClawSubsystem.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystem/DrivebaseSubsystem.java

Updated positions, dropped the lift to "intake" level at the end of auto

Gabriel's Saturday night work

---

Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/ControlsCoDriver.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/ControlsDriver.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/ControlsOperator.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/Hardware.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/command/arm/ElbowServoIncrementalDownCommand.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/command/arm/ElbowServoIncrementalUpCommand.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/command/arm/FlipperServoIncrementalDownCommand.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/command/arm/FlipperServoIncrementalUpCommand.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/command/drive/ApplySnailModeCommand.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/command/drive/ApplyTurboModeCommand.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/opmode/auto/JustVisionPark.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/opmode/diagnosis/ClawArmServoTest.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/opmode/diagnosis/FixTheVision.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/opmode/teleop/RegularMecanumDrive.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/subsystem/ArmSubsystem.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/subsystem/MecanumDriveSubsystem.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/subsystem/VisionPipeline.java

Dumping 16750 LM2 code into main

---

ForTeaching/build.gradle
Sixteen750/build.gradle
Twenty403/build.gradle
build.dependencies.gradle
package.json
scripts/libflip.js
settings.gradle

and back. Very helpful when debugging/fixing issues with things like the 8.1.1 SDK.

Added some stuff to allow easy flipping from a local to maven TechnoLib

---

Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystem/ClawSubsystem.java

Update the claw constants for the newly printed claw (not sure about them, though)

Claw update

---

Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/autonomous/AutoConstants.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/autonomous/AutoTestDrivebaseCommand.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/autonomous/right/AutoRightCycleLeft.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/autonomous/right/AutoRightCycleMiddle.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/autonomous/right/AutoRightCycleRight.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/autonomous/right/AutoRightFullCycle.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/autonomous/right/AutoRightSingleCycleOne.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/autonomous/right/AutoRightSingleCycleThree.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/autonomous/right/AutoRightSingleCycleTwo.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/drive/AutoSpeedCommand.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmode/LeftFullCycle.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmode/RightFullCycle.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystem/ClawSubsystem.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystem/DrivebaseSubsystem.java

Not fully validated, but generally safe.

Alternate coordinates, faster 20403 auto driving 

---

.gitignore
scripts/libflip.js

Commented the libflip script a little, added node_modules to .gitignore

---

Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/drive/DriveCommand.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/drive/TileMoveCommand.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/controls/ControlDriver.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmode/testing/TeleVisionTest.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystem/DrivebaseSubsystem.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystem/VisionPipeline.java

Tio, take a look at these changes, then approve the PR to get them into the TeleVision branch. The one I think may have been causing our core problem is in TeleVisionTest.java at about line 40, where I *don't* schedule the 'normal' VisionCommand, so it doesn't stop the vision pipeline. Hopefully stuff starts working 🤷

Some random cleanup of stuff I saw poking around TeleVision

---

Twenty403/src/main/java/org/firstinspires/ftc/twenty403/Hardware.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/Robot.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/autonomous/AutoConstants.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/drive/DriveCommand.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystem/DrivebaseSubsystem.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystem/OdoSubsystem.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystem/OverrideLocalizer.java

The color & distance sensors appear to be providing some value for localization :)

Use odometry: Color & Distance sensors: W00t!

---

Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/drive/DriveCommand.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystem/DrivebaseSubsystem.java

Bump up the acceleration & velocity for RoadRunner, and fixed the rotation adjustment for teleop driving. Raven handles MUCH better now.

Sped up both Auto driving and Tele rotating

---

Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystem/VisionPipeline.java

Moved the camera, fixed the view port for Signal

---

Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystem/ClawSubsystem.java

Fixed claw constants after a gear skip incident

---

Twenty403/src/main/java/org/firstinspires/ftc/twenty403/Hardware.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/autonomous/AutoConstants.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/autonomous/left/AutoLeftParkLeft.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/autonomous/right/AutoRightParkingLeft.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/autonomous/right/AutoRightParkingMiddle.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/autonomous/right/AutoRightParkingRight.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/autonomous/right/AutoRightPreLoadLeft.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/autonomous/right/AutoRightPreLoadMiddle.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/command/autonomous/right/AutoRightPreLoadRight.java
build.dependencies.gradle

I believe these are changes from Gabriel at League Meet 2

Changes left on blue laptop

---

package.json

Fixed a typo in the script file

---

ForTeaching/src/main/java/org/firstinspires/ftc/forteaching/TechnoBot/Hardware.java
package.json

I missed a usage of the old SDK 8.0 IMU because the bot was disabled...

Fixed an SDK 8.1.1 problem with ForTeaching

---

ForTeaching/build.gradle
Sixteen750/build.gradle
Swerveteen750/build.gradle
Twenty403/build.gradle
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmode/testing/RevEncoderTest.java
build.dependencies.gradle
build.gradle
package.json
scripts/flip.js
settings.gradle

This is for testing Rev Thru-bore encoders. Validated on an encoder plugged into Raven.
It also includes a few script modifications because I like having automation :)

Rev thru encoder test

---

Swerveteen750/src/main/java/org/firstinspires/ftc/swerveteen750/opmode/diagnosis/SwervePodVelocityPIDTuner.java
Swerveteen750/src/main/java/org/firstinspires/ftc/swerveteen750/subsystem/drive/DriveConstantsForPidTuner.java
Swerveteen750/src/main/java/org/firstinspires/ftc/swerveteen750/subsystem/drive/SwerveDriveForVelocityTuning.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmode/testing/DriveVelocityPIDTuner.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmode/testing/RevEncoderTest.java

RoadRunner PID Tuning stuff
